"""What every artifact is.

Imports nothing but `shared.errors` -- a leaf that itself imports nothing, so
a document can refuse with the library's own error without growing an edge.
And that is load-bearing: if a document's dataclass lived in
the component that produces it, `cut` would import `boundaries` to read a
timeline, growing exactly the edges the file-handoff design removes. Every
component imports a shape from here; none imports another.

The split against the components is shape versus derivation --
`Timeline.index_at` is shape, `grid.enforce` is derivation.

These dataclasses are also the source for `db/json/*.schema.json`, generated by
`schemas.py` rather than maintained beside them.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from typing import Any, Optional
from ..errors import Refused

#: Rounding for identity and serialisation. Boundaries come from float
#: arithmetic over two independent clocks, so comparing them exactly would
#: report drift that is not there. A millisecond is far finer than any boundary
#: decision this pipeline makes.
PRECISION = 3


def _round(value: Optional[float]) -> Optional[float]:
    return None if value is None else round(value, PRECISION)


def _hash(payload: dict[str, Any]) -> str:
    """A short, stable hash of a document's identifying content.

    `sort_keys` is not cosmetic. `jsonb` preserves array order but not object
    key order -- it stores keys by (length, bytewise) -- so a document read back
    from Postgres hands back its keys in a different order from the file. A
    hash over iteration order would then differ by where the document was read
    from, which is a bug `falconvar` shipped and had to chase down.
    """
    text = json.dumps(payload, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]


# --------------------------------------------------------------------------
# 1 · media  --  what the file is
# --------------------------------------------------------------------------

@dataclass(frozen=True)
class VideoStream:
    """How to open and address the picture.

    ``time_base`` is carried as a string ("1/12800") rather than a float:
    ``pts * time_base`` is exact rational arithmetic, and at timebases this
    fine a rounded float lands on the wrong frame. JSON has no rational type,
    so the exact form has to survive as text.
    """

    #: Its stream index in the container, which is what a decoder is told to
    #: open.
    index: int
    #: The codec name as the container reports it, e.g. `h264`.
    codec: str
    #: Frames per second, averaged. None when the container will not say -- a
    #: variable-rate file, or a stream with no frame count.
    rate: Optional[float]
    #: The stream's own clock, as `num/den`. A `pts` means nothing without it,
    #: and at 1/1200000 a rounded float lands on a different frame.
    time_base: Optional[str]
    #: Coded width in pixels, before any rotation metadata.
    width: int
    #: Coded height in pixels, before any rotation metadata.
    height: int
    #: How many frames the container claims. None when it does not say, and
    #: advisory even when it does.
    frames: Optional[int]
    #: This stream's own duration. The two streams routinely disagree --
    #: 205.280 s of video against 205.264 s of audio on the reference file --
    #: which is why the grid uses `Media.duration_s` instead.
    duration_s: Optional[float]

    def as_dict(self) -> dict[str, Any]:
        return {"index": self.index, "codec": self.codec, "rate": self.rate,
                "time_base": self.time_base, "width": self.width,
                "height": self.height, "frames": self.frames,
                "duration_s": _round(self.duration_s)}

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "VideoStream":
        return cls(index=d["index"], codec=d["codec"], rate=d.get("rate"),
                   time_base=d.get("time_base"), width=d["width"],
                   height=d["height"], frames=d.get("frames"),
                   duration_s=d.get("duration_s"))


@dataclass(frozen=True)
class AudioStream:
    """How to open the soundtrack. Deliberately not the waveform."""

    #: Its stream index in the container.
    index: int
    #: The codec name as the container reports it, e.g. `aac`.
    codec: str
    #: Samples per second. None when the container will not say.
    rate: Optional[int]
    #: How many channels. None when the container will not say.
    channels: Optional[int]
    #: This stream's own duration; see `VideoStream.duration_s`.
    duration_s: Optional[float]

    def as_dict(self) -> dict[str, Any]:
        return {"index": self.index, "codec": self.codec, "rate": self.rate,
                "channels": self.channels, "duration_s": _round(self.duration_s)}

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "AudioStream":
        return cls(index=d["index"], codec=d["codec"], rate=d.get("rate"),
                   channels=d.get("channels"), duration_s=d.get("duration_s"))


@dataclass(frozen=True)
class Media:
    """One file, seen as the two streams it feeds.

    ``duration_s`` is the *container's*, and it is the one both halves must
    agree to use. The streams routinely disagree -- 205.280 s of video against
    205.264 s of audio on the reference file -- and a grid built from the
    shorter one leaves the tail of the longer outside every chunk.
    """

    #: The id every later component is addressed by, and the name of the
    #: directory they write into. The filename stem by default -- but read it
    #: off `Produced.video_id` rather than assuming, because a *different* file
    #: wanting a taken id is given a new one.
    video_id: str
    #: Where the file was when it was described. `audio` and `video` open this,
    #: so a file that has moved must be re-described.
    path: str
    #: The container as the demuxer names it, e.g. `mov,mp4,m4a,3gp,3g2,mj2`.
    container_format: str
    #: The *container's* duration, and the one both halves must agree to use.
    #: None when the container reports none, which makes a grid underivable.
    duration_s: Optional[float]
    #: The picture stream, or None if the file carries none.
    video: Optional[VideoStream]
    #: The soundtrack stream, or None if the file carries none.
    audio: Optional[AudioStream]
    #: What file this is, independently of where it sits or what it is called.
    #: A video id is the filename stem by default, so two different videos
    #: named `clip.mp4` claim one output directory -- and the corruption that
    #: follows is silent, because each document stays well-formed on its own.
    #: This is what lets `media` tell "the same file again", which must reuse
    #: the directory or resume is defeated, from "a different file with that
    #: name", which must not. See `split.fingerprint`.
    #:
    #: Optional because a `media.json` written before this existed has none,
    #: and there is no way to compute one for a file that may have moved.
    source: Optional[str] = None

    @property
    def has_video(self) -> bool:
        return self.video is not None

    @property
    def has_audio(self) -> bool:
        return self.audio is not None

    def as_dict(self) -> dict[str, Any]:
        return {
            "document": "media", "version": 1,
            "video_id": self.video_id,
            "path": self.path,
            "container_format": self.container_format,
            "duration_s": _round(self.duration_s),
            "video": self.video.as_dict() if self.video else None,
            "audio": self.audio.as_dict() if self.audio else None,
            "source": self.source,
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "Media":
        return cls(
            video_id=d["video_id"], path=d["path"],
            container_format=d["container_format"],
            duration_s=d.get("duration_s"),
            video=VideoStream.from_dict(d["video"]) if d.get("video") else None,
            audio=AudioStream.from_dict(d["audio"]) if d.get("audio") else None,
            source=d.get("source"),
        )


# --------------------------------------------------------------------------
# 2 · raw transcript  --  what was said, before any grid exists
# --------------------------------------------------------------------------

@dataclass
class RawTranscript:
    """Words, segments and speaker turns. **No chunks.**

    Stored before it is cut, and that is the asymmetry the whole ordering
    argument rests on. Whisper timestamps every word, so this can be re-cut to
    any grid, any number of times, without touching a model -- while a
    sampler's decisions are made during a decode pass and cannot be revisited.
    Keeping the ungridded record as a file is what lets a grid change without
    re-running inference; `falconvar` holds it in memory and discards it.

    ``turns`` is empty when no diarizer ran, and every segment then keeps
    ``speaker: None``. A transcript with no speaker information is truthful;
    one where everything is `SPEAKER_00` is not.
    """

    #: Which video this is the soundtrack of.
    video_id: str
    #: Which transcriber and diarizer produced this, and under what settings.
    #: Half of what makes a stored result comparable to a new one.
    model: dict[str, Any] = field(default_factory=dict)
    #: What the decoded audio was: sample rate, channels, duration, and the RMS
    #: and peak that decide silence.
    track: dict[str, Any] = field(default_factory=dict)
    #: Whisper's own utterances, each with `start`, `end`, `text` and a
    #: `speaker` attributed by duration. **No chunk ids** -- applying a grid is
    #: `cut`'s job, and keeping them out is what makes re-cutting free.
    segments: list[dict[str, Any]] = field(default_factory=list)
    #: One entry per word with its own `start`/`end`, and the `speaker` whose
    #: turn its *midpoint* falls in. The midpoint, because the two models
    #: estimate edges independently and a word span routinely straddles a turn
    #: boundary.
    words: list[dict[str, Any]] = field(default_factory=list)
    #: Diarization's spans: who spoke from when to when, before any text is
    #: attached.
    turns: list[dict[str, Any]] = field(default_factory=list)
    #: Headline numbers -- segments, words, speakers, turns, speech seconds,
    #: attributed words, and the three timings.
    stats: dict[str, Any] = field(default_factory=dict)

    @property
    def speakers(self) -> list[str]:
        seen = {t.get("speaker") for t in self.turns}
        return sorted(s for s in seen if s)

    @property
    def silent(self) -> bool:
        return bool(self.track.get("silent", False))

    def as_dict(self) -> dict[str, Any]:
        return {
            "document": "raw_transcript", "version": 1,
            "video_id": self.video_id,
            "model": self.model,
            "track": self.track,
            "speakers": self.speakers,
            "segments": self.segments,
            "words": self.words,
            "turns": self.turns,
            "stats": self.stats,
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "RawTranscript":
        return cls(video_id=d["video_id"], model=d.get("model", {}),
                   track=d.get("track", {}), segments=d.get("segments", []),
                   words=d.get("words", []), turns=d.get("turns", []),
                   stats=d.get("stats", {}))


# --------------------------------------------------------------------------
# 3 · cuts  --  raw boundary evidence, before any guard
# --------------------------------------------------------------------------

@dataclass
class Cuts:
    """Interior cut times, plus the score series they were thresholded from.

    ``scores`` is the point of this document, not ``cuts``. A cut list is a
    *thresholding* of the series, so keeping the series makes re-thresholding
    arithmetic over a cached array instead of another pass over the video --
    the same expensive-half / cheap-half split `falconvar`'s calibrator uses
    for samplers: run the model once per frame, compare thousands of times.

    That matters most because the detector is strided. It scores the difference
    between *consecutive frames it was given*, so at stride 5 it compares
    moments 200 ms apart rather than 40 ms, and a threshold calibrated for
    adjacent frames fires far more often. Every real cut survives a stride;
    false positives are what rise. Caching the scores is what makes finding the
    new threshold free.
    """

    #: Which video these boundaries were found in.
    video_id: str
    #: Which modality they came out of: `video` for a scene pass, `audio` for a
    #: speech one. What `retune` reads to know which module can re-threshold
    #: them.
    source: str                      # "video" | "audio"
    #: What found them -- `content` for the scene detector, or the policy name
    #: for a speech pass. A grid refuses cuts whose detector does not match its
    #: policy.
    detector: str                    # "content" | "vad" | "speaker"
    #: The settings that pass ran under, so a stored result says what produced
    #: it.
    params: dict[str, Any] = field(default_factory=dict)
    #: The boundary timestamps themselves, in media seconds.
    cuts: list[float] = field(default_factory=list)
    #: The per-frame score series, kept so a different threshold is arithmetic
    #: over a cached array rather than a second decode -- verified identical to
    #: a full re-run at 0.12 ms against 5.9 s. None for a detector with no
    #: continuous score.
    scores: Optional[dict[str, Any]] = None
    #: How many cuts, over how many scored frames, and at what rate.
    stats: dict[str, Any] = field(default_factory=dict)

    def as_dict(self) -> dict[str, Any]:
        return {
            "document": "cuts", "version": 1,
            "video_id": self.video_id,
            "source": self.source,
            "detector": self.detector,
            "params": self.params,
            "cuts": [_round(c) for c in self.cuts],
            "scores": self.scores,
            "stats": self.stats,
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "Cuts":
        return cls(video_id=d["video_id"], source=d["source"],
                   detector=d["detector"], params=d.get("params", {}),
                   cuts=list(d.get("cuts", [])), scores=d.get("scores"),
                   stats=d.get("stats", {}))


# --------------------------------------------------------------------------
# 4 · timeline  --  THE GRID
# --------------------------------------------------------------------------

@dataclass
class Timeline:
    """Where every chunk starts and ends, and what decided it.

    `chunk_id` is the index into ``spans``, and it is a key three other
    documents inherit. A chunk is simultaneously the unit a describer
    summarises, the unit a transcript is cut into and the unit retrieval
    returns -- so if the picture and the soundtrack disagreed about where a
    boundary falls, one query would return two different clips with no honest
    way to say which is the answer.
    """

    #: Which video this grid divides.
    video_id: str
    #: `(start_s, end_s)` per chunk, in order and contiguous. The chunk id is
    #: the index into this list, which is why nothing may renumber it.
    spans: list[tuple[float, float]]
    #: How the boundaries were decided: `uniform`, `scene`, `vad` or `speaker`.
    policy: str = "uniform"                       # uniform|scene|vad|speaker
    #: The settings this grid was built under -- the chunk length, the floor
    #: and ceiling, and whatever the evidence pass recorded.
    params: dict[str, Any] = field(default_factory=dict)
    #: "video", "audio", or "grid" when the policy is arithmetic and neither
    #: modality had to run. Recorded because a reader otherwise cannot tell a
    #: propagated boundary from a natively derived one.
    derived_from: str = "grid"

    def __len__(self) -> int:
        return len(self.spans)

    @property
    def duration_s(self) -> float:
        return self.spans[-1][1] if self.spans else 0.0

    def bounds_of(self, chunk_id: int) -> tuple[float, float]:
        """Start and end. Never an open end -- a supplied grid is complete, and
        that is the difference from a chunker deriving one as it streams."""
        return self.spans[chunk_id]

    def index_at(self, ts: float) -> Optional[int]:
        """Which chunk contains ``ts``. The last chunk owns its own end."""
        for index, (start, end) in enumerate(self.spans):
            if start <= ts < end:
                return index
        if self.spans and ts == self.spans[-1][1]:
            return len(self.spans) - 1
        return None

    def nearest(self, ts: float) -> int:
        """``index_at``, but never None.

        Media time outside the grid happens at the tail: the audio stream is
        routinely a few milliseconds shorter than the video one, so the last
        frames of a file can fall past a grid derived from the soundtrack. The
        nearest edge chunk owns them rather than the frame being dropped or a
        chunk being invented for it.
        """
        index = self.index_at(ts)
        if index is not None:
            return index
        if not self.spans:
            raise Refused("an empty timeline contains no chunk")
        return 0 if ts < self.spans[0][0] else len(self.spans) - 1

    def fingerprint(self) -> str:
        """A hash of the grid and the policy that produced it.

        Every document cut on this grid records it. If two disagree, they were
        cut on different grids and `chunk_id` means two different things --
        which becomes a comparison a reader can make rather than a drift that
        nothing reports.
        """
        return _hash({
            "spans": [[_round(s), _round(e)] for s, e in self.spans],
            "policy": self.policy,
            "params": self.params,
        })

    def as_dict(self) -> dict[str, Any]:
        return {
            "document": "timeline", "version": 1,
            "video_id": self.video_id,
            "policy": self.policy,
            "derived_from": self.derived_from,
            "params": self.params,
            "fingerprint": self.fingerprint(),
            "duration_s": _round(self.duration_s),
            "chunk_count": len(self.spans),
            "chunks": [{"chunk_id": i, "start_ts": _round(s), "end_ts": _round(e)}
                       for i, (s, e) in enumerate(self.spans)],
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "Timeline":
        return cls(
            video_id=d["video_id"],
            spans=[(float(c["start_ts"]), float(c["end_ts"]))
                   for c in sorted(d["chunks"], key=lambda c: c["chunk_id"])],
            policy=d.get("policy", "uniform"),
            params=d.get("params", {}),
            derived_from=d.get("derived_from", "grid"),
        )


# --------------------------------------------------------------------------
# 5 · manifest  --  which frames were kept, why, and how to fetch them again
# --------------------------------------------------------------------------

@dataclass
class Manifest:
    """What each sampler kept from each chunk.

    **No `start_ts` / `end_ts`.** Those belong to the grid, and one copy of the
    grid is the whole point -- `falconvar` stores the spans in `video_chunks`
    *and* `audio_chunks` with nothing constraining them to agree. A reader
    joins on `chunk_id` and gets them from `timeline.json`.

    ``manifest_fingerprint`` is a hash of the source minus its uri, and the
    config minus the frame store. So it is known before the first chunk exists,
    survives the video and the store being moved, and changes when the sampling
    changes. Staleness downstream is a comparison against it, never a deletion:
    re-ingesting costs seconds where describing costs inference.
    """

    #: Which video was ingested.
    video_id: str
    #: The grid this was cut on. Everything cut on a grid records this, so two
    #: documents that disagree were cut on different ones and `chunk_id` means
    #: two different things.
    timeline_fingerprint: str
    #: What was decoded: the path, the container, the duration and the video
    #: stream's own facts. This is what `recovery/` rebuilds a store from,
    #: which is why it is copied here rather than referenced.
    source: dict[str, Any] = field(default_factory=dict)
    #: The decimator, every sampler's own configuration, and where frames went.
    #: Authoritative: `recovery/` reads this and imports nothing from the
    #: pipeline, so a default living in code rather than here would go
    #: untested.
    config: dict[str, Any] = field(default_factory=dict)
    #: Frames decimated, frames sampled, chunks, and -- when frames were kept
    #: -- how many files and how many megabytes. `frames_sampled` is picks and
    #: `stored_frames` is files, and they are different numbers.
    stats: dict[str, Any] = field(default_factory=dict)
    #: [{chunk_id, decimated_frames, samplers: {id: {frame_count, frames[]}}}]
    chunks: list[dict[str, Any]] = field(default_factory=list)

    def fingerprint(self) -> str:
        return _hash({
            "source": {k: v for k, v in self.source.items() if k != "path"},
            "config": {k: v for k, v in self.config.items()
                       if k != "frame_store"},
        })

    def sampler_ids(self) -> list[str]:
        return [s["id"] for s in self.config.get("samplers", [])]

    def frames_of(self, chunk_id: int, sampler_id: str) -> list[dict[str, Any]]:
        for chunk in self.chunks:
            if chunk["chunk_id"] == chunk_id:
                block = chunk.get("samplers", {}).get(sampler_id)
                return list(block["frames"]) if block else []
        return []

    def as_dict(self) -> dict[str, Any]:
        return {
            "document": "manifest", "version": 1,
            "video_id": self.video_id,
            "timeline_fingerprint": self.timeline_fingerprint,
            "manifest_fingerprint": self.fingerprint(),
            "source": self.source,
            "config": self.config,
            "stats": self.stats,
            "chunks": self.chunks,
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "Manifest":
        return cls(video_id=d["video_id"],
                   timeline_fingerprint=d.get("timeline_fingerprint", ""),
                   source=d.get("source", {}), config=d.get("config", {}),
                   stats=d.get("stats", {}), chunks=d.get("chunks", []))


# --------------------------------------------------------------------------
# 6 · transcript  --  what was said, on the grid
# --------------------------------------------------------------------------

@dataclass
class Transcript:
    """The raw transcript cut to chunks.

    **Chunks with no speech are kept, with empty text.** The grid is shared, so
    `chunk_id` must mean the same thing here as in the manifest; dropping the
    quiet ones renumbers everything after them and breaks that correspondence
    silently.

    Only `speakers` goes into `structured`, never `turns`. For a description
    the structured half is worth embedding because it holds what the summary
    does not; but `turns[].text` *is* the transcript, so rendering it would
    append the whole chunk a second time interleaved with timestamps read as
    numbers. The turns are the record and stay on the chunk.
    """

    #: Which video this is the soundtrack of.
    video_id: str
    #: The grid it was cut on; see `Manifest.timeline_fingerprint`.
    timeline_fingerprint: str = ""
    #: Carried through from the `RawTranscript`, so a cut transcript still says
    #: which models produced the words.
    model: dict[str, Any] = field(default_factory=dict)
    #: One entry per chunk of the grid, with its text, words, turns and
    #: speakers. **Chunks with no speech are kept, with empty text**: the grid
    #: is shared, so dropping the quiet ones would renumber everything after
    #: them.
    chunks: list[dict[str, Any]] = field(default_factory=list)
    #: Chunks, how many carry speech, words placed against words in the
    #: transcript, words that fell outside the grid, and speakers.
    stats: dict[str, Any] = field(default_factory=dict)

    def text_of(self, chunk_id: int) -> str:
        for chunk in self.chunks:
            if chunk["chunk_id"] == chunk_id:
                return chunk.get("text", "")
        return ""

    def as_dict(self) -> dict[str, Any]:
        return {"document": "transcript", "version": 1,
                "video_id": self.video_id,
                "timeline_fingerprint": self.timeline_fingerprint,
                "model": self.model, "stats": self.stats,
                "chunks": self.chunks}

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "Transcript":
        return cls(video_id=d["video_id"],
                   timeline_fingerprint=d.get("timeline_fingerprint", ""),
                   model=d.get("model", {}), chunks=d.get("chunks", []),
                   stats=d.get("stats", {}))


# --------------------------------------------------------------------------
# 7 · descriptions  --  one answer per (chunk, sampler)
# --------------------------------------------------------------------------

@dataclass
class Descriptions:
    """What a model said about each chunk, per sampler.

    Keyed by `sampler_id`, which for a pairing is `name:prompt` -- so
    `yolo:overview` and `clip:overview` stay distinct while asking one
    question. `model` carries a hash of the prompt module as well as the model
    id: editing a prompt changes the output but not the model name, and a
    resume that ignored it would report "10 skipped" having done nothing.
    """

    #: Which video was described.
    video_id: str
    #: The grid it was described against; see `Manifest.timeline_fingerprint`.
    timeline_fingerprint: str = ""
    #: Which ingest produced the frames. Part of the resume key: a re-ingest
    #: that chose different frames invalidates the answers about them.
    manifest_fingerprint: str = ""
    #: Which describer, under what settings, and `{question: hash}` for every
    #: prompt asked. Per question rather than one hash over the vocabulary, so
    #: *adding* a question -- which cannot change an existing answer -- does
    #: not invalidate every description of every video.
    model: dict[str, Any] = field(default_factory=dict)
    #: One entry per chunk, holding a block per sampler id with that call's
    #: summary and structured answer. There is deliberately no chunk-level
    #: rollup: flattening every sampler's answer into one record forced a
    #: winner for a shared key, and nothing read it.
    chunks: list[dict[str, Any]] = field(default_factory=list)
    #: Described, skipped, failed, and the elapsed time.
    stats: dict[str, Any] = field(default_factory=dict)

    def done(self) -> set[tuple[int, str]]:
        """Which (chunk, sampler) pairs already have an answer."""
        return {(c["chunk_id"], sid)
                for c in self.chunks for sid in c.get("samplers", {})}

    def as_dict(self) -> dict[str, Any]:
        return {"document": "descriptions", "version": 1,
                "video_id": self.video_id,
                "timeline_fingerprint": self.timeline_fingerprint,
                "manifest_fingerprint": self.manifest_fingerprint,
                "model": self.model, "stats": self.stats,
                "chunks": self.chunks}

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "Descriptions":
        return cls(video_id=d["video_id"],
                   timeline_fingerprint=d.get("timeline_fingerprint", ""),
                   manifest_fingerprint=d.get("manifest_fingerprint", ""),
                   model=d.get("model", {}), chunks=d.get("chunks", []),
                   stats=d.get("stats", {}))


# --------------------------------------------------------------------------
# 8 · embedded  --  what text was embedded. For reading, not for searching.
# --------------------------------------------------------------------------

@dataclass
class Embedded:
    """What `embed` produced: every unit's text, hash and vector.

    **This is the output of embedding, not a readable copy of it.** It held no
    vectors while a `VectorIndex` did -- Qdrant or Postgres -- and this file
    was the human-readable half beside them. With the index gone, the vectors
    have nowhere else to live, and having them here is what lets a re-run
    resume: a unit whose `text_hash` is unchanged under the same embedder does
    not need paying for twice.

    It still answers the question it always did -- *what text did this chunk
    actually contribute* -- which is the one asked when a ranking looks wrong,
    and the measurement that established embedding the summary *and* the
    structured fields (0.705 against 0.528 MRR).

    **One file per video, and now one embedder at a time.** `units.render()`
    produces the same text whichever model embeds it, so the readable half was
    shared; the vectors are not, so the document names the embedder that made
    them and is rewritten whole when that changes. Postgres still holds several
    at once -- every row carries the embedder and every query filters on it --
    because a table is not rewritten whole.
    """

    #: Which video these units belong to.
    video_id: str
    #: The grid they were built on; see `Manifest.timeline_fingerprint`.
    timeline_fingerprint: str = ""
    #: Who made the vectors, as `embedders.build().key` -- model and width.
    #: A vector is only comparable inside the space that produced it, so this
    #: is what a reader checks before trusting one, and what resume compares.
    embedder: str = ""
    #: One entry per embeddable unit: the text, its hash, and `vector`, the
    #: floats themselves. `vector` is absent on a unit that was never embedded.
    units: list[dict[str, Any]] = field(default_factory=list)

    def text_of(self, chunk_id: int, sampler_id: str) -> str:
        for unit in self.units:
            if unit["chunk_id"] == chunk_id and unit["sampler_id"] == sampler_id:
                return unit.get("content", "")
        return ""

    def as_dict(self) -> dict[str, Any]:
        return {"document": "embedded", "version": 2,
                "video_id": self.video_id,
                "timeline_fingerprint": self.timeline_fingerprint,
                "embedder": self.embedder,
                "count": len(self.units),
                "samplers": sorted({u["sampler_id"] for u in self.units}),
                "units": self.units}

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "Embedded":
        return cls(video_id=d["video_id"],
                   timeline_fingerprint=d.get("timeline_fingerprint", ""),
                   embedder=d.get("embedder", ""),
                   units=d.get("units", []))

    def stored(self) -> dict[str, str]:
        """`{unit key: text_hash}` for every unit that has a vector.

        What resume reads. A unit with no vector is one that was collected but
        never embedded, so it must not count as stored -- that is the same
        mistake as an index reporting a row it wrote with an empty embedding.
        """
        return {f"{self.video_id}:{u['chunk_id']}:{u['sampler_id']}":
                u.get("text_hash", "")
                for u in self.units if u.get("vector")}


# --------------------------------------------------------------------------
# 9 · aggregate  --  video-level structure over what the chunks said
# --------------------------------------------------------------------------

@dataclass
class Aggregate:
    """One aggregator's answer about the whole video.

    ``inputs_fingerprint`` is a hash of the chunk text actually read. A summary
    of descriptions that have since been rewritten reads perfectly, which is
    precisely why staleness cannot be left to a reader to notice.
    """

    #: Which video was answered about.
    video_id: str
    #: Which aggregate this is, e.g. `summary` or `entities:actors`. A colon
    #: cannot be in a Windows filename, so it is stored as
    #: `entities.actors.json` and no name contains a dot.
    aggregate_id: str
    #: The cost ceiling it ran under: `free`, `local` or `llm`.
    tier: str
    #: The answer itself, shaped by the definition that produced it.
    payload: dict[str, Any] = field(default_factory=dict)
    #: A hash of the chunk text actually read. A summary of descriptions since
    #: rewritten reads perfectly, which is why staleness cannot be left to a
    #: reader to notice.
    inputs_fingerprint: str = ""
    #: Headline numbers, and `model` for an llm aggregate -- without which
    #: switching `--llm` reused the stored answer and reported success.
    stats: dict[str, Any] = field(default_factory=dict)

    def as_dict(self) -> dict[str, Any]:
        return {"document": "aggregate", "version": 1,
                "video_id": self.video_id, "aggregate_id": self.aggregate_id,
                "tier": self.tier, "inputs_fingerprint": self.inputs_fingerprint,
                "payload": self.payload, "stats": self.stats}

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "Aggregate":
        return cls(video_id=d["video_id"], aggregate_id=d["aggregate_id"],
                   tier=d.get("tier", "free"), payload=d.get("payload", {}),
                   inputs_fingerprint=d.get("inputs_fingerprint", ""),
                   stats=d.get("stats", {}))


# --------------------------------------------------------------------------
# 10 · excerpt and sightings  --  what ONE aggregate reads, as a file
# --------------------------------------------------------------------------

@dataclass
class Excerpt:
    """The rows one selection took from a record: what a text aggregate reads.

    **The whole input of `summary`, `chapters`, `events`, `ner`, `sentiment`
    and every custom prompt**, so each of them is a component with one file in
    and one file out. `select` writes it; the selection that chose the rows is
    kept beside them, and so is the grid they came from -- a row's times are
    resolved from it when it is written, and `chapters` still needs the whole
    grid to say whether every chunk was covered. Nothing else is read.

    A row is `{chunk_id, start_ts, end_ts, parts: [[source, text], ...]}`:
    one chunk, with what each source said about it, in source order. Chunks
    the selection found nothing in are absent.
    """

    #: Which video -- or combination -- the rows were taken from.
    video_id: str
    #: The input as written, e.g. `transcript+clip:activity`. Carried because
    #: an answer records what it read, and because it is how an answer made
    #: from this file is told apart from one made from another selection.
    selection: str
    #: The grid, as `timeline.json` holds it. Embedded rather than referenced,
    #: so the file is the whole input; `Timeline.from_dict` reads it back.
    timeline: dict[str, Any] = field(default_factory=dict)
    #: One entry per chunk that the selection found something in.
    rows: list[dict[str, Any]] = field(default_factory=list)
    #: The answer ids that contributed, and `transcript` when it did.
    answers: list[str] = field(default_factory=list)

    def as_dict(self) -> dict[str, Any]:
        return {"document": "excerpt", "version": 1, "video_id": self.video_id,
                "selection": self.selection, "count": len(self.rows),
                "answers": self.answers, "timeline": self.timeline,
                "rows": self.rows}

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "Excerpt":
        return cls(video_id=d["video_id"], selection=d.get("selection", ""),
                   timeline=d.get("timeline", {}), rows=d.get("rows", []),
                   answers=d.get("answers", []))


@dataclass
class Sightings:
    """The mentions one link profile reads: every entry that might be someone.

    The input of `entities`, and the reason it is not an `Excerpt`: linking
    reads *entries* -- one person in one answer, with every key the describer
    gave -- not rendered text, and it needs to know which answer each came from,
    because two entries of one answer are different people by the question's
    own wording. That is the cannot-link rule, and it survives the file.
    """

    #: Which video -- or combination -- the mentions were taken from.
    video_id: str
    #: The link profile they were selected for, e.g. `people`. An entities run
    #: under a different profile is refused: identity keys are the profile's.
    profile: str
    #: The input as written, e.g. `*` or `yolo[people.clothing]`.
    selection: str
    #: The list field linked, e.g. `people`, or `transcript` / `summary` for a
    #: whole-value profile.
    field_name: str = ""
    #: The identity keys each mention is signed by -- the profile's, or fewer
    #: when the selection narrowed them.
    keys: list[str] = field(default_factory=list)
    #: The grid, as `timeline.json` holds it: an entity's span and time on
    #: screen are resolved from it.
    timeline: dict[str, Any] = field(default_factory=dict)
    #: `{chunk_id, sampler_id, field, index, signature, entry}` per mention.
    mentions: list[dict[str, Any]] = field(default_factory=list)
    #: `{chunk_id: what was said}` for the chunks mentioned, only when the
    #: profile's account reads the transcript. Empty otherwise.
    transcript: dict[str, str] = field(default_factory=dict)

    def as_dict(self) -> dict[str, Any]:
        return {"document": "sightings", "version": 1, "video_id": self.video_id,
                "profile": self.profile, "selection": self.selection,
                "field": self.field_name, "keys": self.keys,
                "count": len(self.mentions), "timeline": self.timeline,
                "mentions": self.mentions, "transcript": self.transcript}

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "Sightings":
        return cls(video_id=d["video_id"], profile=d.get("profile", ""),
                   selection=d.get("selection", ""), field_name=d.get("field", ""),
                   keys=d.get("keys", []), timeline=d.get("timeline", {}),
                   mentions=d.get("mentions", []),
                   transcript={str(k): v for k, v in (d.get("transcript") or {}).items()})


def fingerprint_of(payload: dict[str, Any]) -> str:
    """A stable hash of arbitrary content. Exposed for components that need
    their own staleness key -- `inputs_fingerprint`, `text_hash`."""
    return _hash(payload)


# --------------------------------------------------------------------------
# what every component hands back
# --------------------------------------------------------------------------

@dataclass
class Produced:
    """What a component actually wrote.

    A bare path would be shorter and say less. This reports the real output:
    no ``store`` on a run with the frame store off, no ``transcript`` on a
    silent file, and the stats a progress callback wants -- so a caller learns
    what happened rather than assuming from what it asked for.
    """

    #: Which video, and **the answer rather than the argument**: `media` may
    #: mint a new id when a different file wants a taken one, so later calls
    #: read it from here.
    video_id: str
    #: Which component produced this. `boundaries.evidence` answers as
    #: `boundaries.video` or `boundaries.audio`, naming which modality supplied
    #: the cuts -- which is not knowable before it runs.
    component: str
    #: `{artifact name: where it went}`. Lists what *was* written rather than
    #: what could be: a run with no frame store has a manifest and no store,
    #: and a caller should learn that from here rather than by looking.
    artifacts: dict[str, str] = field(default_factory=dict)
    #: The component's headline numbers. What is in here is the component's
    #: business; `component` says whose vocabulary to read it in.
    stats: dict[str, Any] = field(default_factory=dict)
    #: What did not happen, and it is an answer rather than an absence --
    #: `boundaries.evidence` under `uniform` returns `skipped: [evidence]`
    #: rather than nothing, so one call answers the same way over HTTP and from
    #: an import.
    skipped: list[str] = field(default_factory=list)

    def path(self, name: str) -> str:
        return self.artifacts[name]

    def as_dict(self) -> dict[str, Any]:
        return {"video_id": self.video_id, "component": self.component,
                "artifacts": self.artifacts,
                "stats": self.stats, "skipped": self.skipped}


def same_video(**documents: Any) -> str:
    """The one id these documents agree on, or a refusal naming the argument.

    Here because it is a fact about documents rather than about storage: every
    one of them carries its own `video_id`, and a component works on one
    video. Needs nothing but that attribute, so it does not cost this module
    the import-nothing rule.

    Addressed by video id this could not happen -- `paths.artifact(id, name)`
    is a join, so two artifacts read under one id are that video's by
    construction. Addressed by path it can, and a pipeline keeping every file
    in one folder makes it rare rather than impossible. So the check is
    written down once, where a caller wiring components by hand also gets it.
    """
    seen = {name: doc.video_id for name, doc in documents.items()
            if doc is not None}
    ids = set(seen.values())
    if len(ids) > 1:
        detail = ", ".join(f"{name}={vid!r}" for name, vid in sorted(seen.items()))
        raise Refused(
            f"these documents are not the same video: {detail}. "
            f"Each carries its own id, and a component works on one video.")
    return next(iter(ids)) if ids else ""


DOCUMENTS = {"media": Media, "raw_transcript": RawTranscript,
             "cuts": Cuts, "timeline": Timeline, "manifest": Manifest,
             "transcript": Transcript, "descriptions": Descriptions,
             "embedded": Embedded,
             "aggregate": Aggregate,
             "excerpt": Excerpt, "sightings": Sightings}

__all__ = ["PRECISION", "VideoStream", "AudioStream", "Media",
           "RawTranscript", "Cuts", "Timeline", "Manifest", "Transcript",
           "Descriptions", "Embedded", "Aggregate", "Excerpt", "Sightings",
           "Produced", "fingerprint_of", "DOCUMENTS", "same_video"]
